### ISSUE TITLE
`denote-get-identifier-at-point` fails with "Wrong type argument: stringp, denote-link-ol-help-echo"

### ISSUE THREAD

**Issue by brabalan** [protesilaos/denote#449] opened 2024-09-23 13:22 UTC
In the function `denote-get-identifier-at-point`, the call to `get-text-property position 'help-echo` return the symbol `denote-link-ol-help-echo`. As a consequence, the `string-match` right after fails as it’s not a string.

**Comment by protesilaos** [comment] 2024-09-23 17:57
Oops! This is a regression caused by a change I made (added a `:help-echo`, which is useful).

Does this work for you?

```elisp
(defun denote-get-identifier-at-point (&optional point)
  "Return the Denote identifier at point or optional POINT."
  (when-let ((position (or point (point)))
             (face-at-point (get-text-property position 'face))
             (_ (or (eq face-at-point 'denote-faces-link)
                    (member 'denote-faces-link face-at-point))))
    (or (get-text-property position 'denote-link-id)
        (when-let ((link-data (get-text-property position 'htmlize-link))
                   (link (cadr link-data)))
          (string-match denote-id-regexp link)
          (match-string-no-properties 0 link)))))
```

**Comment by brabalan** [comment] 2024-09-24 09:35
Yes, it works, thanks!

**Comment by protesilaos** [comment] 2024-09-26 05:09
Very well! I just pushed the change. Closing now.

**Closed by protesilaos** 2024-09-26 05:09 UTC
