### ISSUE TITLE
Merge `refactor-denote-prompts` and delete `denote--prompts`

### ISSUE THREAD

**Issue by jeanphilippegg** [protesilaos/denote#41] opened 2022-07-09 20:55 UTC
I am creating this issue following my comment in pull request #33 . I don't have any new code beside what is already in the existing `refactor-denote-prompts` branch.

I would like to have a discussion about the function `denote--prompts` (the one that normalizes the values of `denote-prompts`).

- Case (iii): This is just to ignore unrecognized values from `denote-prompts`. It does not seem useful, since the `denote` command already ignores unrecognized symbols.
- Case (ii): If `denote-prompts` is nil, I think we should do as the user probably wanted by setting it to nil, which is no prompts. `denote--prompts` arranges for the title and the keywords to be prompted in that case.
- Case (i): This case checks that the value of `denote-prompts` is a list. I am not sure this is necessary. In `denote`, `dolist` over anything that is not a list will throw an error. Maybe this is sufficient?

What do you think?

**Comment by protesilaos** [comment] 2022-07-10 04:10
I think `denote--prompts` is no longer necessary.  When I wrote it we did not yet support the file permutations, so I thought it was needed to prevent the creation of unsupported file names.  Now we are okay.

**Comment by jeanphilippegg** [comment] 2022-07-10 04:10
Ok, good!

**Comment by jeanphilippegg** [comment] 2022-07-10 04:15
We can use this branch to see if there are any issues. Before merging into `main`, we may want to rework section 3 of the manual to reflect the modifications. Here is the outline I propose:

```
3. Points of entry
3.1 The `denote` command
    [Essentially the same info as the docstring of `denote`.]
3.2 Customizing the prompts
    [How to get the desired prompts. Convenience functions could be quickly summarized here.]
3.3 Create note using Org capture
    [Same as before.]
```

**Comment by protesilaos** [comment] 2022-07-10 04:20
Looks good!  Though we can do that last.  Do you think the code is finalised?  We can proceed to a round of testing.  If all works, then we change the manual and merge everything.

**Comment by jeanphilippegg** [comment] 2022-07-10 04:25
> Though we can do that last.

Sure!

> Do you think the code is finalised?

On my side, I believe it is! I have one very small pull request coming in a few minutes, but it is not really related.

**Comment by protesilaos** [comment] 2022-07-10 04:27
Okay, I will start working on the final details and merge it.

**Comment by protesilaos** [comment] 2022-07-10 08:03
What do you think about this instead of the `called-interactively-p` we had before?

```elisp
(defun denote (&optional title keywords type date subdir)
  "Create a new note with the appropriate metadata and file name.

When called interactively, the metadata and file name are prompted
according to the value of `denote-prompts'.

When called from Lisp, all arguments are optional.

- TITLE is a string or a function returning a string.  If nil, an
  empty string is used.

- KEYWORDS is a list of strings.  The list can be empty or the
  value can be set to nil.

- TYPE is a symbol among those described in `denote-file-type'.

- DATE is a string representing a date like 2022-06-30 or a date
  and time like 2022-06-16 14:30.  A nil value or an empty string
  is interpreted as the `current-time'.

- SUBDIR is a string representing the path to either the value of
  the variable `denote-directory' or a subdirectory thereof.  The
  subdirectory must exist: Denote will not create it."
  (interactive
   (let (args)
     (dolist (prompt denote-prompts)
       (pcase prompt
         ('title (push (denote--title-prompt) args))
         ('date (push (denote--date-prompt) args))
         ('file-type (push (denote--file-type-prompt) args))
         ('subdirectory (push (denote--subdirs-prompt) args))
         ('keywords (push (denote--keywords-prompt) args))))
     args))
  (let* ((denote-file-type (denote--file-type-symbol (or type denote-file-type)))
         (date (if (or (null date) (string-empty-p date))
                   (current-time)
                 (denote--valid-date date)))
         (id (format-time-string denote--id-format date))
         (denote-directory (or subdir (denote-directory))))
    (denote--barf-duplicate-id id)
    (denote--prepare-note (or title "") keywords nil date id)
    (denote--keywords-add-to-history keywords)))
```

**Comment by jeanphilippegg** [comment] 2022-07-10 15:19
I tested with `'(keywords title date)` and I get an error.

Calling `denote` non interactively seems to work, but I don't understand why.

**Comment by jeanphilippegg** [comment] 2022-07-10 15:23
I have an idea.

**Comment by jeanphilippegg** [comment] 2022-07-10 15:46
This works!

```elisp
  (interactive
   (let ((args (make-vector 5 nil)))
     (dolist (prompt denote-prompts)
       (pcase prompt
         ('title (aset args 0 (denote--title-prompt)))
         ('keywords (aset args 1 (denote--keywords-prompt)))
         ('file-type (aset args 2 (denote--file-type-prompt)))
         ('date (aset args 3 (denote--date-prompt)))
         ('subdirectory (aset args 4 (denote--subdirs-prompt)))))
     (append args nil)))
```

**Comment by jeanphilippegg** [comment] 2022-07-10 15:53
Also, I have not given much thought to the order of the arguments, but it would be the right time. Maybe `date` should be 3rd and `file-type` last?

**Comment by protesilaos** [comment] 2022-07-10 16:14
> Also, I have not given much thought to the order of the arguments, but it would be the right time.

Yes, this is the right time to do it.  In the `denote-prompts` we document them in this order:

- title
- keywords
- date
- file-type
- subdirectory

So whatever change we make, I suggest we keep those in sync.

Also:

```elisp
(defun denote (&optional title keywords type date subdir)
```

I think we should use `file-type` there for consistency.  For the private functions, it does not matter, but for the publicly-facing ones we need to apply the same terminology.  What do you think?

To your salient point, I think `title` and `keywords` should be 1st and 2nd: they are the most common ones.  For the others I do not really mind.  In my workflow, the `date` would be the least used one, so I would put it last.  Between `file-type` and `subdirectory`, I do not know.

**Comment by jeanphilippegg** [comment] 2022-07-10 16:40
> What do you think?

I agree!

> Between `file-type` and `subdirectory`, I do not know.

I do not mind either for the last 3 parameters.

**Comment by protesilaos** [comment] 2022-07-10 16:54
> I do not mind either for the last 3 parameters.

Since you do not mind, I say we do `title keywords file-type subdirectory date`.  I will update the docs and everything.  Okay?

**Comment by jeanphilippegg** [comment] 2022-07-10 17:18
> Okay?

Yes!

**Comment by protesilaos** [comment] 2022-07-10 17:51
Okay.  Will do it later, or tomorrow morning depending on how things go now.

**Comment by protesilaos** [comment] 2022-07-10 18:08
Try this to see what the problem is:

```elisp
(defun denote--file-name-relative-to-denote-directory (file)
  "Return file name of FILE relative to the variable `denote-directory'.
FILE must be an absolute path."
  (when-let* ((dir (denote-directory))
              (file-name (expand-file-name file))
              ((string-prefix-p dir file-name)))
    ;; (substring-no-properties file-name (length dir))
    (format "%s %s" dir file-name)
    ))
```

The `expand-file-name` without a check for an absolute path.

**Comment by protesilaos** [comment] 2022-07-10 18:10
Indeed, `(expand-file-name "subdir/20220710T210519--a-nested-note__test.txt")` returns the wrong path.

**Comment by protesilaos** [comment] 2022-07-10 18:11
Whereas this returns the expected value (only tested this scenario):

```elisp
(defun denote--file-name-relative-to-denote-directory (file)
  "Return file name of FILE relative to the variable `denote-directory'.
FILE must be an absolute path."
  (when-let* ((dir (denote-directory))
              (file-name (expand-file-name (file-name-nondirectory file)))
              ((string-prefix-p dir file-name)))
    ;; (substring-no-properties file-name (length dir))
    (format "%s %s" dir file-name)
    ))
```

**Comment by protesilaos** [comment] 2022-07-10 18:35
I just realise I posted these last comments in the wrong thread...  Sorry!  They are meant for [issue 42](https://github.com/protesilaos/denote/pull/42)

**Comment by protesilaos** [comment] 2022-07-11 03:39
> Since you do not mind, I say we do `title keywords file-type subdirectory date`.  I will update the docs and everything.

Will now finalise this and merge the branch.

**Comment by protesilaos** [comment] 2022-07-11 04:36
Just merged everything into `main`.  Please check when you have the time.  We close this afterwards.

**Comment by jeanphilippegg** [comment] 2022-07-11 04:42
In `denote`, you have changed the order or the argument. You should also change the index in the `pcase`.

**Comment by protesilaos** [comment] 2022-07-11 04:44
Oops!  Fixed now.

**Comment by jeanphilippegg** [comment] 2022-07-11 04:45
In the manual, you have this:
```
  This is where the ~denote-date~ command comes in.  It accepts the
  familiar =TITLE= and =KEYWORDS= arguments, though it starts by asking
  for a date.  The input for the =DATE= argument is like =2022-06-16= or
  =2022-06-16 14:30=.  When the time is omitted, it is interpreted as
  =00:00=.
```
The new `denote-date` does not accept any argument anymore. In lisp, one should always use the `denote` function, which accepts all optional arguments.

**Comment by protesilaos** [comment] 2022-07-11 04:46
> In the manual, you have this:

Correct.  I will revise them all to reflect their doc strings.

**Comment by jeanphilippegg** [comment] 2022-07-11 04:48
I suggest this modification:

> To this end, Denote provides the follow**ing** convenience **interactive** commands for note
creation:

**Comment by protesilaos** [comment] 2022-07-11 04:53
Okay, added your suggested modification and update the convenience commands to reflect their doc strings.

**Comment by jeanphilippegg** [comment] 2022-07-11 04:55
Very good! I don't have any other comments!

**Comment by protesilaos** [comment] 2022-07-11 05:00
Thank you!  I say we give it another day or two with this feature set.  Then I prepare a new release.  What do you think?

Closing this, by the way.

**Closed by protesilaos** 2022-07-11 05:00 UTC

**Comment by jeanphilippegg** [comment] 2022-07-11 05:01
> I say we give it another day or two with this feature set. Then I prepare a new release. What do you think?

That's good!
