### ISSUE TITLE
Command denote-dired-rename-file-and-add-front-matter does not add front matter

### ISSUE THREAD

**Issue by hpgisler** [protesilaos/denote#62] opened 2022-07-24 13:21 UTC
The command ```denote-dired-rename-file-and-add-front-matter``` does not seem to work correctly.

### Steps to reproduce
1. Assuming, I have a file ```test.org``` with content 'test'. in my denote folder.
2. ```dired``` opens the folder.
3. put point on ```test.org```
4. ```M-x denote-dired-rename-file-and-add-front-matter```

### Effect
- the file gets renamed on filesystem as requrested
- the follwoing error is shown in ```*Messages*``` buffer:
  ```denote-dired--rename-buffer: Invalid function: (buffer (find-buffer-visiting old-name))```
- the renamed files does not contain the frontmatter (i.e. file content is still 'test'

### Versions
```(version)``` yields: ```"GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.17.6)```
Denote Version (GitHub): ```d3fae65 main origin/main Update the manual's Acknowledgements for 5d245df```

**Comment by protesilaos** [comment] 2022-07-24 13:31
What happens if you `(require 'subr)`?

**Comment by hpgisler** [comment] 2022-07-24 13:43
```(require 'subr)```

enters debugger:

```lisp
Debugger entered--Lisp error: (error "Loading file /usr/share/emacs/28.1/lisp/subr.elc f...")
  require(subr)
  (progn (require 'subr))
  eval((progn (require 'subr)) t)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```
```Messages``` buffers says:

```lisp
progn: Loading file /usr/share/emacs/28.1/lisp/subr.elc failed to provide feature ‘subr’
```

**Comment by protesilaos** [comment] 2022-07-24 13:45
Okay, the problem is that on Emacs 28 this was `(require 'subr-x)`.

**Comment by hpgisler** [comment] 2022-07-24 14:47
Hmm, still the exact same error...

What I've done:
- I've modified ```denote.el``` according to your diff above 
- I've deleted the compiled version, i.e. ```denote.elc``` from my filesystem
- I've restarted emacs

**Comment by protesilaos** [comment] 2022-07-24 14:58
I found it by testing these two on `emacs -Q` with Emacs 28:

```elisp
;; this has an error
(when-let* ((name (buffer-name)))
  (message "%s" name))
```

![Screenshot from 2022-07-24 17-56-09](https://user-images.githubusercontent.com/12828033/180652941-23f59617-a805-4a70-bf3a-1437d919dcd4.png)


```elisp
;; this works
(when-let ((name (buffer-name)))
  (message "%s" name))
```

![image](https://user-images.githubusercontent.com/12828033/180652923-57a20ee1-bb7d-48a8-81a4-d7d5c37e0603.png)

The `when-let*` is legacy code anyway, as we only have one form and don't need the asterisk.

Pushed the change in commit `61e672f`

**Comment by hpgisler** [comment] 2022-07-24 15:03
Great, it now works!

Thank you, Prot!

**Comment by hpgisler** [comment] 2022-07-24 15:08
Note:

There seem to be a couple of other ```when-let*``` in other files.
They should also be changed, shouldn't they?

**Comment by protesilaos** [comment] 2022-07-24 15:16
> Great, it now works!

Very well!

> Thank you, Prot!

You are welcome!

> There seem to be a couple of other when-let* in other files.  They should also be changed, shouldn't they?

I checked them.  The asterisk they have is correctly used in those cases.  I will still need to require `subr-x` the way I mentioned before.

**Comment by protesilaos** [comment] 2022-08-05 03:12
Closing this as it is continued in [issue 74](https://github.com/protesilaos/denote/issues/74).

**Closed by protesilaos** 2022-08-05 03:12 UTC
