### ISSUE TITLE
"denote:" link for non-note files doesn't open

### ISSUE THREAD

**Issue by relict007** [protesilaos/denote#135] opened 2023-02-14 10:03 UTC
I am seeing an issue with `denote:` links to non-note files (i.e. file type not in `denote-file-types`). Links are
created but  throw error when opened .

Steps to see the problem:
1. Copy a non-note file , e.g. a `.jpeg` file to `denote-directory`
2. Open the directory in `dired`
3. Take the cursor to the newly added file
4. Run command `denote-rename-file` 
5. Name the file appropriately when prompted (e.g. "dummy image")
6. Add keyword when prompted (e.g. "personal")
7. Denote asks to rename the file, press `y`  (i.e. yes)
9. Open an existing note and add a link to the newly added file by calling `denote-link`. Notice that link is added.
10. Click the newly added link to open the file (`.jpeg` in my case)

What happens:
File doesn't open and Emacs gives an error

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("::\\(.*\\)\\'" nil)
  org-link-open-as-file(nil nil)
  denote-link-ol-follow("20230214T104246")
  org-link-open((link (:type "denote" :path "20230214T104246" :format bracket :raw-link "denote:20230214T104246" :application nil :search-option nil :begin 150 :end 189 :contents-begin 176 :contents-end 187 :post-blank 0 :parent (paragraph (:begin 150 :end 192 :contents-begin 150 :contents-end 190 :post-blank 2 :post-affiliated 150 :mode nil :granularity element :cached t :parent (section (:begin 1 :end 295 :contents-begin 1 :contents-end 295 :robust-begin 1 :robust-end 293 :post-blank 0 :post-affiliated 1 :mode first-section :granularity element :cached t :parent (org-data ...) :org-element--cache-sync-key (3 . 0))))))) nil)
  org-open-at-point(nil)
  funcall-interactively(org-open-at-point nil)
  call-interactively(org-open-at-point)
  org-return(1)
  (if (org-in-src-block-p) (org-return) (org-return 1))
  (lambda nil (interactive) (if (org-in-src-block-p) (org-return) (org-return 1)))()
  funcall-interactively((lambda nil (interactive) (if (org-in-src-block-p) (org-return) (org-return 1))))
  call-interactively((lambda nil (interactive) (if (org-in-src-block-p) (org-return) (org-return 1))) nil nil)
  command-execute((lambda nil (interactive) (if (org-in-src-block-p) (org-return) (org-return 1))))
```

I am at the Denote commit 828af23.

I went through the discussions in #1 and agree with you that its a bit of stretch for Denote to handle links to binary files and we don't want to go too much in that direction. This scenario can be handled in 2 ways, either we filter out non text files in
`denote-link` so that link is not easily created or we allow the link creation but open it using regular emacs similar to a `file:` link.

**Comment by protesilaos** [comment] 2023-02-15 12:13
@relict007 Can you try this?

```diff
 denote.el | 9 +++------
 1 file changed, 3 insertions(+), 6 deletions(-)

diff --git a/denote.el b/denote.el
index 0b06067..bd4a29d 100644
--- a/denote.el
+++ b/denote.el
@@ -771,12 +771,9 @@ (define-obsolete-function-alias
 (defun denote-get-path-by-id (id)
   "Return absolute path of ID string in `denote-directory-files'."
   (seq-find
-   (lambda (f)
-     (and (string-prefix-p id (file-name-nondirectory f))
-          ;; The directory can contain exported html and other
-          ;; derivative files that have the same name sans extetion as
-          ;; the note.
-          (denote-file-is-note-p f)))
+   (lambda (file)
+     (and (string-prefix-p id (file-name-nondirectory file))
+          (denote-file-has-identifier-p file)))
    (denote-directory-files)))
 
 (define-obsolete-function-alias
```

Note that issue 1 is too old.  We have since made it possible to link to any file with an identifier.

**Comment by protesilaos** [comment] 2023-02-15 12:14
We could add a user option here to retain the old behaviour that is mentioned in the deleted comment.

**Comment by relict007** [comment] 2023-02-15 14:47
> Can you try this?

Yes, it works. The link created in the issue description opens correctly now.

> Note that issue 1 is too old. We have since made it possible to link to any file with an identifier.

Good to know. Denote file name scheme in itself is nice and useful.

> We could add a user option here to retain the old behaviour that is mentioned in the deleted comment.
>
>EDIT: Though I see no reason why those files should not be counted. If the user does not want them, they would delete them, no?

I am not sure about the deleted comment that you are referring here, but I don't think we need any user option
here.  Present behaviour of considering any file with the appropriate name as a _Denote compatible file_ seems
sane to me. It also aligns with the fact that Denote allows users to added any file type as Denote note file.

**Comment by protesilaos** [comment] 2023-02-16 04:59
I just pushed the change:

```
commit e86ab9a04ea9ea347f209ec35a83f08ce5868be4
Author: Protesilaos Stavrou <info@protesilaos.com>
Date:   Thu Feb 16 06:56:43 2023 +0200

    Make denote-get-path-by-id accept any file with an identifier
    
    This is its intended purpose.  The user was already able to, say,
    create 'denote:' links to jpg files but 'denote-get-path-by-id' was
    refusing to resolve the path.
    
    Thanks to user relict007 for reporting the problem and discussing it
    with me in issue 135 on the GitHub mirror:
    <https://github.com/protesilaos/denote/issues/135>.

 README.org | 2 +-
 denote.el  | 9 +++------
 2 files changed, 4 insertions(+), 7 deletions(-)
```

Thank you!

**Comment by nobiot** [comment] 2023-02-16 10:54
@protesilaos @relict007 
If I remember correctly, the comments in `denote-get-path-by-id` were written by me. I cannot have time to ensure what I will be saying below is correct now, but the change that Prot has just introduced might break backlinks and some other related functions in the specific cases alluded to by the comments (hence, I made the function as it was with the comments -- I regret that the comments didn't make this issue clear).

The case is something like this:
1. You have `20230216__mynotes--tag.org`.
2. You export it to `20230216__mynotes--tag.html`.
3. Both files are in `denote-directory`
4. This means you have **two files with the same ID with different extensions**
5. `denote-link-find-file`, `denote-link-find-backlink`, and` xref integration might find the html file INSTEAD OF the .org file

This is because `html` is earlier in the alphabetical order than `org`. Because the function use `seq-find`, it will find the `.html` file first and returns it. 

The previous implementation with the comments, I believe (sorry, again, I'm talking from my memory) was to avoid this case and ensure only the `denote-file` will be returned by `seq-find`.

**Comment by protesilaos** [comment] 2023-02-16 14:57
Thank you @nobiot for explaining this!  I did a `C-x v h` (`M-x vc-region-history`) over the region but did not find a commit that would hint at this and I forgot the discussions associated with it.

Maybe a solution is to have a user option to exclude certain files?  We already have user options `denote-excluded-directories-regexp` and `denote-excluded-keywords-regexp`.

**Comment by nobiot** [comment] 2023-02-16 17:33
@protesilaos alternatively, use the filter function (instead of the find function) and see if it returns more than one files from the same ID? 

Just an idea. Sorry I must go so can't test it.

```diff
 (defun denote-get-path-by-id (id)
   "Return absolute path of ID string in `denote-directory-files'."
-  (seq-find
-   (lambda (file)
-     (and (denote-file-has-identifier-p file)
-          (string-prefix-p id (file-name-nondirectory file))))
-   (denote-directory-files)))
+  (let ((files
+         (seq-filter
+          (lambda (file)
+            (and (denote-file-has-identifier-p file)
+                 (string-prefix-p id (file-name-nondirectory file))))
+          (denote-directory-files))))
+    (if (length< files 2) (car files)
+      (seq-find (lambda (file) (denote-file-is-note-p file)) files))))
```

**Comment by protesilaos** [comment] 2023-02-17 10:36
@nobiot This gets tricky.  The problem can occur with any file that Org exports, such as `.md`.  Then we have no way of knowing which is the source of truth that Denote should refer to.

**Comment by nobiot** [comment] 2023-02-17 11:20
Yes, tricky. One way out is to use `denote-file-type`. When it is nil, use `.org` as Denote's default behaviour (I suggest that it should be changed to a explicit default value, but that's perhaps another topic). This way, it's a user's explicit choice.

The reasoning goes as follows:
- The problem is when a single ID points to multiple files with different extensions. 
- We should exclude the situation when there are multiple files with the same extension. 
- ... So if we can let user decide their "primary" file extension, that's a solution.

**Comment by nobiot** [comment] 2023-02-17 11:29
Like so. The last `or` clause can be removed if we can guarantee that `denote-file-type` always has a value. I don't feel it is aesthetically pleasing so I may be missing something.

```diff
 (defun denote-get-path-by-id (id)
   "Return absolute path of ID string in `denote-directory-files'."
-  (seq-find
-   (lambda (f)
-     (and (string-prefix-p id (file-name-nondirectory f))
-          ;; The directory can contain exported html and other
-          ;; derivative files that have the same name sans extetion as
-          ;; the note.
-          (denote-file-is-note-p f)))
-   (denote-directory-files)))
+  (let ((files
+         (seq-filter
+          (lambda (file)
+            (and (denote-file-has-identifier-p file)
+                 (string-prefix-p id (file-name-nondirectory file))))
+          (denote-directory-files))))
+    (if (length< files 2) (car files)
+      (seq-find (lambda (file) (and (denote-file-is-note-p file)
+                                    (or (string= denote-file-type (file-name-extension file))
+                                        (string= "org" (file-name-extension file)))))                
+                files))))
```

**Comment by protesilaos** [comment] 2023-02-20 07:05
@nobiot

Maybe this?

```diff
(defun denote--get-path-identifiers (id)
  "Return list of file paths matching ID in `denote-directory-files'."
  (seq-filter
   (lambda (file)
     (and (denote-file-has-identifier-p file)
          (string-prefix-p id (file-name-nondirectory file))))
   (denote-directory-files)))

(defun denote-get-path-by-id (id)
  "Return absolute path of ID string in `denote-directory-files'."
  (seq-find
   (lambda (file)
     (and (denote-file-is-note-p file)
          (string-match-p (file-name-extension file)
                          (denote--file-extension denote-file-type))))
   (denote--get-path-identifiers id)))
```

The code for your convenience:

```elisp
(defun denote--get-path-identifiers (id)
  "Return list of file paths matching ID in `denote-directory-files'."
  (seq-filter
   (lambda (file)
     (and (denote-file-has-identifier-p file)
          (string-prefix-p id (file-name-nondirectory file))))
   (denote-directory-files)))

(defun denote-get-path-by-id (id)
  "Return absolute path of ID string in `denote-directory-files'."
  (seq-find
   (lambda (file)
     (and (denote-file-is-note-p file)
          (string-match-p (file-name-extension file)
                          (denote--file-extension denote-file-type))))
   (denote--get-path-identifiers id)))
```

This way we do not need to touch the `denote-file-type`.

**Comment by nobiot** [comment] 2023-02-20 21:25
@protesilaos 

How is this fundamentally different to the original with my comments (pasted below)?
How does your new suggestion return an html export from an denote org file, or jpg image files, for example?

This form `(denote--file-extension denote-file-type)` in your suggestion for me returns ".md" so `denote-get-path-by-id` would return only markdown files if I understand it correctly. It appears to be more restrictive than the original below (??? -- sorry I think I must be missing something).

```emacs-lisp
(defun denote-get-path-by-id (id)
  "Return absolute path of ID string in `denote-directory-files'."
  (seq-find
   (lambda (f)
     (and (string-prefix-p id (file-name-nondirectory f))
          ;; The directory can contain exported html and other
          ;; derivative files that have the same name sans extetion as
          ;; the note.
          (denote-file-is-note-p f)))
   (denote-directory-files)))
```

**Comment by protesilaos** [comment] 2023-02-21 04:33
@nobiot 

> How is this fundamentally different to the original with my comments (pasted below)?

You are right.  I was focused on tweaking the code you sent so that it would use `denote--file-extension` and I forgot the original problem...  We are back to your previous diff then.  My intent is to avoid hardcoding Org.  Maybe this then?

```elisp
(defun denote-get-path-by-id (id)
  "Return absolute path of ID string in `denote-directory-files'."
  (let ((files
         (seq-filter
          (lambda (file)
            (and (denote-file-has-identifier-p file)
                 (string-prefix-p id (file-name-nondirectory file))))
          (denote-directory-files))))
    (if (length< files 2)
        (car files)
      (seq-find
       (lambda (file)
         (denote-file-is-note-p file))
       files))))
```

Put differently, I don't see what the following `or` is guarding against:

```elisp
(or (string= denote-file-type (file-name-extension file))
    (string= "org" (file-name-extension file)))
```

**Comment by nobiot** [comment] 2023-02-21 06:46
> Put differently, I don't see what the following or is guarding against

Guarding against the case where denote-file-type is nil, which I thought was the default according to its document string.

**Comment by nobiot** [comment] 2023-02-21 06:50
My suggestion is to change its default value to be set explicitly to org.

**Comment by nobiot** [comment] 2023-02-21 06:57
> @nobiot This gets tricky. The problem can occur with any file that Org exports, such as `.md`. Then we have no way of knowing which is the source of truth that Denote should refer to.

To the newly suggested code, you have already identified a problematic case. This is the reason I suggested to use denote-file-type.

**Comment by protesilaos** [comment] 2023-02-28 19:43
@nobiot Thanks for the clarification!  Let's do it as you say.  Do you want to send a patch, so that it is recorded in Git as well?

**Comment by nobiot** [comment] 2023-02-28 20:43
@protesilaos Will do... Give me some time. I will try some time this week or weekend.

**Comment by jason0kenyon** [comment] 2023-03-13 14:57
I have been struggling for some time to get `denote-link-find-file` to open file types other than org. In particular, I have been struggling to get pdfs to work (I write in latex and wanted to use the functionality of denote to organize my documents.)

Today I tinkered with the function and made it work. I am, by no means, a programmer, so please let me know if I am not obeying proper etiquette. 
Below is my edited function:
```elisp
(defun denote-link-find-file ()
  "Use minibuffer completion to visit linked file. This is my version that works with arbitrary file types"
  (interactive)
  (if-let* ((current-file (buffer-file-name))
            (file-type (denote-filetype-heuristics current-file))
            (regexp (denote--link-in-context-regexp file-type))
            (files (denote-link--expand-identifiers regexp)))

  (let ((file-names (mapcar #'denote-get-file-name-relative-to-denote-directory
                            files)))
(find-file (completing-read "Jump to file: " file-names)))
    (user-error "No links found in the current buffer")))
```

**Comment by nobiot** [comment] 2023-03-13 16:54
@jason0kenyon Your code has made me realize that the fix has led to another bug (I don't think it's a regression but a new one). I am raising a new issue.

**Comment by protesilaos** [comment] 2023-04-07 07:01
I believe we can close this issue now, since @nobiot fixed what was explain [in issue 142](https://github.com/protesilaos/denote/issues/142).

Please let me know if closing this is a mistake.  I will re-open it.

**Closed by protesilaos** 2023-04-07 07:01 UTC
