### ISSUE TITLE
Templates are not working in denote-org-capture-with-prompts

### ISSUE THREAD

**Issue by psmith1303** [protesilaos/denote#302] opened 2024-03-30 21:26 UTC
I have some templates:

```
 (setq denote-templates
        `((plain . "")
          (resonance . "* ${title}\n:PROPERTIES:\n:Type:\n:Start:\n:Fin:\n:Killed:\n:Rating:\n:Digested:\n:Creator:\n:URL:\n:END:\n\n* Actions\n\n* Key Ideas\n\n** Review\n\n** Quotes\n\n** Notes")
          (memo . ,(concat "* Some heading"
                           "\n\n"
                           "* Another heading"
                           "\n\n"))))

```

The function `denote-template` works as is expected; I am prompted for a template, and the subsequent note includes the template text.

However, when I call `denote-org-capture-with-prompts`, I still get prompted for a template, but the subsequent note does not have the template text in it.  My code looks like this:

```
  (add-to-list 'org-capture-templates
             '("F" "New note with full prompts (with denote.el)" plain
               (file denote-last-path)
               (function
                (lambda ()
                  (denote-org-capture-with-prompts :title :keywords :subdirectory nil :template)))
               :no-save t
               :immediate-finish nil
               :kill-buffer t
               :jump-to-captured t) t)

```
The new note only has the normal title, date, filetags, and identifier.

Is it me (they way I am doing it) or is it a bug.

**Comment by jeanphilippegg** [comment] 2024-03-30 22:27
`(denote-template-prompt)` prompts for a symbol which is used to select the correct string template in `denote-templates`.

I am wondering how you are able to input something in `(denote-template-prompt)`. The way it is coded it is required that there is a match with some symbols in `denote-templates`. Even with the standard `denote` command, it requires a symbol.

**Comment by psmith1303** [comment] 2024-03-30 22:49
Yes, I get prompted for the choice of template in both cases (`denote-template` and `denote-org-capture-with-prompts`). The correct template is selected and used when I try `denote-template`.

**Comment by jeanphilippegg** [comment] 2024-03-31 00:26
I could reproduce this issue. Should be fixed in #303 !

**Comment by jeanphilippegg** [comment] 2024-03-31 00:34
By the way, you may want to consider replacing
```
(lambda () (denote-org-capture-with-prompts :title :keywords :subdirectory nil :template)))
```
with
```
(lambda () (let ((denote-prompts '(title keywords subdirectory template))) (denote-org-capture)))
```
because it is more flexible (supports signature and reordering) and `denote-org-capture-with-prompts` may be removed eventually (maybe).

**Comment by protesilaos** [comment] 2024-03-31 04:09
I merged @jeanphilippegg changes. Thank you!

**Closed by protesilaos** 2024-03-31 04:09 UTC

**Comment by x61** [comment] 2024-06-17 18:51
@jeanphilippegg and @protesilaos, is it possible to use the templates defined in `denote-template` in 'org-capture-template`? For example, can I use **resonance**  in the template defined above in @psmith1303's example? That is 

```
(setq org-capture-templates
        '(
          ("g" "General" resonance
           (file denote-last-path)
           (function
            (lambda ()
              (let ((denote-directory (file-name-as-directory (concat (denote-directory) "general"))
                (denote-prompts '(template))
                (denote-org-capture))))
 …..
```
I tried this and it is still prompting for the template.

**Comment by jeanphilippegg** [comment] 2024-06-18 01:12
If I understand correctly, what you want is to "not prompt for a template and use a specific one automatically". Though this was not the object of this issue, we have added some code to allow that in the latest code (or the upcoming version 3.0.0).

You will have to use the new `denote-use-template` variable. (There are other variants for other file name components.)

Here is an example you can adapt to your needs:

```emacs-lisp
(setq denote-templates '((resonance . "the resonance template")))

(setq org-capture-templates
      '(("g" "General" plain
         (file denote-last-path)
         (function
          (lambda ()
            (let ((denote-directory (file-name-as-directory (concat (denote-directory) "general")))
                  (denote-prompts '(title keywords))
                  (denote-use-template 'resonance))
              (denote-org-capture)))))))
```

This org-capture-template will prompt for a title and keywords and will use the `resonance` template automatically (without prompting).
