### ISSUE TITLE
denote-rename-file-title ==> Destination file xxx already exists

### ISSUE THREAD

**Issue by babusri** [protesilaos/denote#409] opened 2024-08-04 22:28 UTC
Note that I am using denote-rename-file-title and not denote-rename-file.

When I modify the title and hit return I get a message in the minibuffer: Destination file xxx already exists

In the Messages buffer I see:
denote--rename-file: Destination file xxx already exists.

Happens every time.

GNU Emacs 29.1 (build 2, x86_64-w64-mingw32) of 2023-07-30
Latest denote Version: 3.0.8

This may or may not be relevant. I have 2 files in a directory. denote-rename-file-title worked on the first one.
It fails on the second one.

**Comment by protesilaos** [comment] 2024-08-05 04:46
> From: babusri ***@***.***>
> Date: Sun,  4 Aug 2024 15:29:15 -0700
>
> Note that I am using denote-rename-file-title and not denote-rename-file.

> [... 11 lines elided]

> This may or may not be relevant. I have 2 files in a directory.
> denote-rename-file-title worked on the first one. It fails on the
> second one.

Is the problematic file read-only?

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by MirkoHernandez** [comment] 2024-08-05 17:37
I think I had this problem when trying to create a rename function (append keyword). It was related to a dired minor mode. I believe the issue is in  `denote-update-dired-buffers` since it uses revert-buffer which in turn changes the read-only state.

**Comment by babusri** [comment] 2024-08-06 04:58
> From: babusri ***@***.***> Date: Sun, 4 Aug 2024 15:29:15 -0700 Note that I am using denote-rename-file-title and not denote-rename-file. [... 11 lines elided] This may or may not be relevant. I have 2 files in a directory. denote-rename-file-title worked on the first one. It fails on the second one.
> Is the problematic file read-only?
> […](#)
> -- Protesilaos Stavrou https://protesilaos.com

No. It is not read-only.

Babu

**Comment by protesilaos** [comment] 2024-08-06 09:48
@babusri Thank you for the feedback!

@MirkoHernandez We check for a writable file in `denote-rename-file-and-buffer`. This may be the ultimate culprit.

Can either of you evaluate the following and then try to re-run the problematic scenario?

```elisp
(defun denote-rename-file-and-buffer (old-name new-name)
  "Rename file named OLD-NAME to NEW-NAME, updating buffer name."
  (unless (string= (expand-file-name old-name) (expand-file-name new-name))
    (cond
     ((derived-mode-p 'dired-mode)
      (dired-rename-file old-name new-name nil))
     ;; NOTE 2024-02-25: The `vc-rename-file' requires the file to be
     ;; saved, but our convention is to not save the buffer after
     ;; changing front matter unless we absolutely have to (allows
     ;; users to do `diff-buffer-with-file', for example).
     ((and denote-save-buffers (not (buffer-modified-p)) (vc-backend old-name))
      (vc-rename-file old-name new-name))
     (t
      (rename-file old-name new-name nil))))
  (when-let ((buffer (find-buffer-visiting old-name)))
    (with-current-buffer buffer
      (set-visited-file-name new-name nil t))))
```

CC @relict007 because this is [the same case as in issue 402](https://github.com/protesilaos/denote/issues/402)

**Comment by babusri** [comment] 2024-08-07 05:04
@protesilaos 
No it does not fix the issue.

Before I evaluated the defun denote-rename-file-and-buffer, I wanted to see if I could reproduce the issue with the same file that existed earlier. I could not. Rename works every time on that file, which didn't work a few days back.

Note: I am not sure if visiting the file before renaming is relevant or not.

Then I created a new denote file in the same directory. denote-rename-file-title did not work and gave me the same error message.

Than I eval'ed the denote-rename-file-and-buffer.
After evaluation, I tried denote-rename-file-title on the same file and I get the same error.

Let me know if you want to me to try something else.

Babu

**Comment by babusri** [comment] 2024-08-07 05:22
@protesilaos 

I started emacs with a different init-directory, where I only had

(straight-use-package 'denote)

That is, I removed consult, vertico, marginalia, ef-themes and the rest.

I cannot reproduce this issue.
I did not have to run your defun.

So, this is likely to be some interaction with some other mode --- my guess is consult.

Babu

**Comment by babusri** [comment] 2024-08-07 05:54
@protesilaos 
I started emacs with a different init-directory, where I only had

(straight-use-package 'denote)

That is, I removed consult, vertico, marginalia, ef-themes and the rest.

I cannot reproduce this issue.
I did not have to run your defun.

So, this is likely to be some interaction with some other mode --- my guess is consult.

**emacs-1**: _I am running my usual emacs with all the packages where I see this problem, with or without evaluating your defun._

**emacs-2**: I _am also running an emacs with just denote_.

In emacs-1, I created a denote file 20240806T224120--rust-what-is-it__rust.org
When I denote-rename-file-title and change title to what-is-it, I get
denote--rename-file: The destination file ‘c:/Users/babu/AppData/Roaming/git/denote/rust/20240806T224120--rust-what-is-it__rust.org’ already exists
Eval you defun, same result.

In emacs-2, I
denote-rename-file-title and change title to what-is-it, and it works fine.

I can repeat this behavior in both emacs-1 and emacs-2 by changing the title back to rust-what-is-it.

Babu

**Comment by MirkoHernandez** [comment] 2024-08-14 05:12
@babusri I had this error recently when trying to remove a keyword.  I used the `denote-rename-keywords` command, then in the promp  pressing RET generated the error, but it worked when using M-RET. Maybe this is an issue when using vertico, disabling the mode, allows the rename command to work  by just pressing RET.

**Comment by babusri** [comment] 2024-08-16 19:59
@MirkoHernandez As I mentioned, I have no packages except denote.

Babu

**Comment by MirkoHernandez** [comment] 2024-08-17 04:06
> So, this is likely to be some interaction with some other mode --- my guess is consult.

I had the issue running vertico, as described in the previous post.

**Comment by jeanphilippegg** [comment] 2024-08-26 02:27
If you are using Vertico, you need to make sure that your prompt is selected (with `M-p` or using `M-Ret`). This is a known behaviour of Vertico and it is documented in section "4.1 Rename a single file" of the Denote manual.

I also get the error message in the title of this issue, using Vertico, if I do not select my new title prompt (and thus keep the old one).

@babusri, from what you wrote in your previous comment, it looks like you only have the issue when you have other packages (Vertico?) installed (emacs-1). If so, can you test the above explanation (using `M-p` or `M-Ret` with Vertico to select your new title)?

**Comment by babusri** [comment] 2024-08-27 08:19
@jeanphilippegg @MirkoHernandez @protesilaos 
Thanks for pointing out Sec 4.1 of the doc.
Sorry for wasting your time.
Please close it as not an issue.

Thanks
Babu

**Comment by protesilaos** [comment] 2024-08-28 07:57
Okay, closing now. Thanks!

**Closed** 2024-08-28 07:57 UTC
Labels: bug
